name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Check MSBuild
      shell: cmd
      run: |
        where msbuild
        msbuild -version

    - name: Generate Visual Studio solution
      shell: cmd
      run: |
        generate.bat

    - name: Build Release (VS2022)
      shell: cmd
      run: msbuild build\shield-development.sln /p:Configuration=Release /p:Platform=x64


    - name: Upload XInput DLL
      uses: actions/upload-artifact@v4
      with:
        name: XInput9_1_0.dll
        path: build/**/XInput9_1_0.dll
        retention-days: 1
